### ISSUE TITLE
Compilation error at Datapoint.hpp

### ISSUE THREAD

**Issue by j0ta29** [bertmelis/VitoWiFi#103]
Datapoint.hpp:76:58: error: static member function 'static const std::vector<IDatapoint*>& IDatapoint::getCollection()' cannot have cv-qualifier

**Comment by bertmelis** [comment]
Fixed in https://github.com/bertmelis/VitoWiFi/commit/7007ea44c653023ce89ef8db18764051019c02a8

Will publish a new version to platformio later.
