### ISSUE TITLE
readDatapoint.ino crashes on ESP32

### ISSUE THREAD

**Issue by Empor-co** [bertmelis/VitoWifi#3]
Hi,

I tried to run the example on a Adafruit HUZZAH32 – ESP32 Feather Board and switched Serial and Serial1 for better debugging.
Sadly the example keeps crashing when calling VitoWifi.loop(); in the loop.

Any ideas?

Thank you in advance.

Best regards,

E-co

**Comment by bertmelis** [comment]
I'll check this evening (only havze a Wemos Lolin32 at my disposal, but the behaviour should be the same). To be honest, I only have tested the esp8266 which is working 
Is there any crash info? (stack dump)

**Comment by bertmelis** [comment]
Could it be that I didn't mind the pin mappings in the examples?
I didn't specify any pins in the examples to avoid `ifdef`-clutter. But it renders the examples unusable on the ESP32.
Furthermore, I also didn't implement the pin mapping in the Optolink.
I can override `VitowifiClass::setup(HardwareSerial* serial)` with `VitowifiClass::setup(HardwareSerial* serial, int8_t rxPin, int8_t txPin)` and subsequently override `Optolink::begin(HardwareSerial* serial);` with `Optolink::begin(HardwareSerial* serial, int8_t rxPin, int8_t txPin)`.

**Comment by Empor-co** [comment]
Shouldn't this be part of the hardware serial lib?
(https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/HardwareSerial.cpp)

**Comment by bertmelis** [comment]
On the Huzzah, you can use RX and TX for the pins as these are defined but Serial1 is not defined/initialized by default.

**Comment by Empor-co** [comment]
This is my current setup:
![vito-esp32](https://user-images.githubusercontent.com/32220981/30815343-34510ad6-a213-11e7-8478-502cdef76193.png)

**Comment by bertmelis** [comment]
could you test with the test-esp32 branch?
I've only tested myself using the globalCallback-esp32 example.

**Comment by Empor-co** [comment]
Compiles nicely and doesn't crash.
Adjusted   VitoWifi.setup(&Serial1, 16, 17); to match 16=RX and 17=TX.
Will check it with the Vito tomorrow.

**Comment by bertmelis** [comment]
I tested globalCallback-esp32 myself with a Wemos Lolin32 on a Vitodens 200, with Vitotronic 200, type HO1. I'd love to hear your feedback.
Main developement is on a esp8266 as I try to keep it online for stability testing (which is in doubt for the moment).

**Comment by Empor-co** [comment]
The code seems to be stable now - just my board setup seems to be wrong: None of the codes I sent, are recognized. Maybe I got the wrong transmit diode.....

**Comment by bertmelis** [comment]
make sure there's no "optical shortcut" and that the optics are aligned. I'll look into the types of parts I have.

**Comment by bertmelis** [comment]
I use a SFH309FA (24°) transistor (with black body!) and a SFH487-2 led, both 3mm versions. I followed this guide: http://openv.wikispaces.com/Bauanleitung+ESP8266.

**Comment by Empor-co** [comment]
That link was the base of my setup the SFH487-2 seems to be end-of-sales, but I was able to get some at ebay. Will try to better seperate the diodes and better shield the vito receiver from any disturbing light....work in progress

**Comment by Empor-co** [comment]
![vito](https://user-images.githubusercontent.com/32220981/31045994-b48d304a-a5f0-11e7-8e5d-1e75eba20936.png)
Tried to build a cap to prevent the optical shortcut, but no luck so far.

**Comment by bertmelis** [comment]
where does it hang? Does it stay in the "reset" state?

I'm working on the docs with pictures from my setup.

You could also try to power up the heating (toggle mains power) while the optocoupler is attached. On mine, the heating won't start. It's a sign that the coupler works.

**Comment by Empor-co** [comment]
Yes, reset state.
Heating starts are usual.
I guess I have to wait for the other LEDs I ordered... ;-)

**Comment by Empor-co** [comment]
One step further: my heating doesn't use the 300 protocol, but the KW protocol, which also starts with a heartbeat of 5s, but is stateless. Have to figure out how to "synchronize" to the heartbeat in order to destinguish the heartbeat from the answer...

**Comment by bertmelis** [comment]
The KW protocol is on my to do-list.
Closing this one in favor to #4
