### ISSUE TITLE
ack followed by nack timeout.

### ISSUE THREAD

**Issue by s0170071** [bertmelis/VitoWiFi#40]
just tried your new version 1.0 on my WO1B/Vitocal300
Based on your raw example I tried data points 0x5525, 0x810 and 0x812.
None of them was on my list before, so I don't know if they work. 
Odd thing, however, is that 0x5525 gives a ack nack timeout reply.

```
READ 4105000155250282
ack
nack, timeout
1
READ 4105000108100220
ack
RCV 41070101081002000023
ack
Address 810 has value 0000FE
READ 4105000108120222
ack
RCV 41070101081202000025
ack
Address 812 has value 0000FE
```

**Comment by bertmelis** [comment]
stale issue.

feel free te reopen if the issue is still present. consider testing v3.
