### ISSUE TITLE
Contradiction in data point list

### ISSUE THREAD

**Issue by andreasloe** [bertmelis/VitoWiFi#44]
There is a contradiction in the data point lists:

VitoWiFi/doc/vt200ho1abc_en.pdf says party modus is read/write on 0x2330.

VitoWiFi/doc/20C2_Vitodens_200_300_333_Vitotronic_200_Typ_HO1.pdf says the address should be 0x2303. 

What is correct?

**Comment by bertmelis** [comment]
Just try and see what's working for you. Your heater will return an error when you rook the wrong one.

**Comment by bertmelis** [comment]
Closing, issue is beyond my control
