### ISSUE TITLE
Read/Write buffer: fixed size

### ISSUE THREAD

**Issue by kollera** [bertmelis/VitoWiFi#50]
### Installation specifics
* **Heating type:** Vitotronic 200
* **Protocol:** KW
* **Board:** ESP8266

### Symptom
Reading/Writing Datapoint KW with length > 4 does not work.
### Extra info
First of all: Outstanding work!

I set MAX_DP_LENGTH to 8 to read  'cycle time' datapoints (DPRaw) with length 8, but got weird return values.
After digging into the code i figured out read/write buffers are limited to 4/6 bytes.
But i'm not an expert, so please have a look at my hack! :)

[diff.txt](https://github.com/bertmelis/VitoWiFi/files/2520894/diff.txt)

**Comment by bertmelis** [comment]
I tried to fix in the branch "MAX_DP_LENGTH".
Also applied to P300 protocol.
