### ISSUE TITLE
Callback with old value after write datapoint

### ISSUE THREAD

**Issue by maihacke** [bertmelis/VitoWiFi#52]
I create a bridge between vitowifi and openhab via mqtt.
Therefore I implemented a method which publishes all read values via mqtt as global callback.
Therefore I call readAll values in the esp loop. Then the global callback of vitowifi publishes all values via mqtt. That works quite well.
For writing thr sketch listens to mqtt and call writeDataPoint accordingly.
The problem is, that immediately after the write the global callback is called with the old value and this outdated value gets published via mqtt.

Is there a reason why vitowifi calls the callback with the old value after a write? I think the callback should not be invoked at all for writes.

What do you think?

**Comment by maihacke** [comment]
Im using KW. I will double check what happens and report it here.

**Comment by maihacke** [comment]
It was just an error in my type conversion logic.
Btw: Thanks for this cool project.

**Comment by maihacke** [comment]
Code is here: https://github.com/maihacke/vitohab
Please notice it is heavily in progress.
Writing is not ready yet...

**Comment by FulvioSpelta** [comment]
Thank you very much. I'd like to have a red-only device at the moment.

**Comment by maihacke** [comment]
I will write a readme for openhab item definitions etc when I find the time...

**Comment by bertmelis** [comment]
For the record: there's an example in [issue 45](https://github.com/bertmelis/VitoWiFi/issues/45).

I'm running a service on my RPI3 (Raspbian latest) with the code in this repo: [Mqtt2InfluxDB](https://github.com/bertmelis/Mqtt2InfluxDB)
