### ISSUE TITLE
Implement GWG protocol

### ISSUE THREAD

**Issue by Arty68** [bertmelis/VitoWiFi#62]
Hello I have a vitodens 100 wb1. 
I have the "Bauanleitung-ESP8266" + esp-link and vitocontold (I also tried with python script which are also working for low level read).
I just began research for the adresses.
I had some results with this : https://github.com/openv/openv/issues/442
I am very interrested about your work.
Would be nice to use vitowifi for GWG protocol also

PS : I have already forked your project here : https://github.com/Arty68/VitoWiFi/tree/master/src and tried to add GWG Support but I could use some help to check if everything is ok :)

**Comment by bertmelis** [comment]
I don't own a Viessmann heating anymore (at least temporary). I can help but I can't test obviously.

Your code is in your repo?

**Comment by Arty68** [comment]
Hi Bertmelis
Thank you for answering so quickly !
First of all Happy New Year :)
Yes I have put it [here](https://github.com/Arty68/VitoWiFi/tree/master/src) the moment.
I am not sur if everything is ok.
You can have a look when you have time
![image](https://user-images.githubusercontent.com/20853780/71711408-2ba06b80-2e01-11ea-81f1-f043529395a8.png)

**Comment by Arty68** [comment]
Hello

I have continued the GWG but not have tested it.

https://github.com/bertmelis/VitoWiFi/compare/master...Arty68:master

**Comment by bertmelis** [comment]
Sorry to keep you waiting. I'll have a look in the next few days.

Now, I see you have it implemented using the master branch. My idea would be to -as soon as it is working- move it over to the V2 branch. I'm happy to do this for you.

**Comment by Arty68** [comment]
No Problem. I will try to test it once I get a little free time.
Thank you to take time to review it.

**Comment by Arty68** [comment]
Hello

I have continued the GWG implementing but still not have tested it.
It's not compiling yet . I still have problem with the template yet in the VitoWifi.cpp line 126.
Also have a GWG test in the example directory.

**Comment by bertmelis** [comment]
I'm still alive :smile:
I'll take a look. It's OK for you to test it against the V2 branch? I'd like to move away from the current master branch. V2 should be easier to deal with.

I can also make an example for you. What do you want to do with the obtained data? Display on webserver? Send via MQTT?

**Comment by Arty68** [comment]
Thanks for the answer. I will try to use the v2 branche. I am not a C++ expert but I will try. Glad that you are still alive :) . Take care. I am from France by the way. Alsace to be more precise.

**Comment by alfredolo72** [comment]
hello, any news on gwg protocol ?

**Comment by bertmelis** [comment]
first version (untested!) added in v3-development

**Comment by alfredolo72** [comment]
i will be happy to test it. I have a Vitodens 200. Right now cannot compile it for esp32, i try to fix errors

**Comment by bertmelis** [comment]
Ours is older and is able to use the VS2 protocol. I suggest you also use this.

**Comment by bertmelis** [comment]
Closing, GWG is implemented in v3. It's untested though. Create a new issue when problems arise.
