### ISSUE TITLE
[OT] WifiPrinter

### ISSUE THREAD

**Issue by sude22** [bertmelis/VitoWiFi#63]
Hi Bert,
sorry for this OffTopic issue, but I could not find out how to contact you direct.
Could you please give a hint what happened to the "https://github.com/bertmelis/WifiPrinter" library?

I used it in some former projects....

**Comment by bertmelis** [comment]
It was hopelessly outdated and I remover the public repo. I can look on my computer to see if I have something left there...

But otherwise, it is not that hard to recreate from scratch. You just want to print messages to clients connected to a specific port?

**Comment by sude22** [comment]
I have a local copy, but I was just curious if it vanished for some special reason.
It was very useful for debugging when the serial connection was used for other stuff (like the Vito communication ;)
I removed it in most of the newer projects because it seems that it leads to Wifi connection errors with the homie framework, but I didn't had a closer look at that.

Thanks for your good work.

**Comment by bertmelis** [comment]
If I remember correctly it uses the blocking version of the TCP server so it could very well mess up if mixed with Homie (which is async).

**Comment by sude22** [comment]
OK, that would be an explanation. I thought it was async implemented because it used a loop method...

**Comment by bertmelis** [comment]
Drafted something quickly: https://github.com/bertmelis/WiFiPrinter
