### ISSUE TITLE
Please tell me the request address V100 boiler pump in operation or not / It is not in the list of addresses of Viessmann-adresses

### ISSUE THREAD

**Issue by dima-357** [bertmelis/VitoWiFi#66]
### Installation specifics
* **Heating type:** eg. 20CB - Vitodens 200 with Vitotronic 200
* **Protocol:** KW or P300
* **Board:** ESP8266 or ESP32 (others?), possible brand/make (NodeMCU, Wemos D1 mini...)
* **Hardware:** Which hardware implementation did you use?

### Symptom
What happens? (crash, unresponsive, nothing at all...)  
When does it happen? (after several hours, immideately...)  
What would you expect?  
...

Be as complete as you can!

### Extra info
Please add relevant debug information like debug messages, (decoded) stack traces...

*You don't have to provide all the info, but less is not always more!*

**Comment by dima-357** [comment]
Please tell me the request address V100
boiler pump in operation or not /
It is not in the list of addresses of Viessmann-adresses

**Comment by bertmelis** [comment]
If it's not in the list, then I don't know.

I don't have a list of every data point for every type of heating.
